[view]
dot = "â—"
select = ">"

[ollama]
url = "http://localhost:11434"
model = "qwen3:8b"
environment_info = "Here is useful information about the environment you are running in:\n"
message_limit  = 100
default_system_message_length = 10
default_tool_size = 10
default_request_contents_size = 10
default_tool_call_size = 5
default_active_stream_size = 10

[mcp]
name = "DevCode"
version = "1.0.0"

[server]
name = "DevCode"
version = "1.0.0"

[prompt]
system = "./SystemPrompt/Root.md"

[tool]
allowed = ["Read","List"]

[bus]
pool_size = 10000
